import 'package:map_rate/features/currency/currency_info.dart';

/// UI 言語の種類（国名表示用）。
enum LocaleKey {
  en,
  ja,
  zh,
  zhTw,
  hi,
  es,
  ko,
  de,
  fr,
  pt,
  ptBr,
  id,
}

/// Flutter の [Locale] 相当の情報から [LocaleKey] を決める。
LocaleKey fromLocale(String languageCode, [String? countryCode, String? scriptCode]) {
  final lang = languageCode.toLowerCase();
  final country = countryCode?.toUpperCase();
  final script = scriptCode?.toLowerCase();

  if (lang == 'pt' && country == 'BR') return LocaleKey.ptBr;
  if (lang == 'zh') {
    if (country == 'TW' || country == 'HK' || country == 'MO' || script == 'hant') {
      return LocaleKey.zhTw;
    }
    return LocaleKey.zh;
  }
  switch (lang) {
    case 'ja':
      return LocaleKey.ja;
    case 'hi':
      return LocaleKey.hi;
    case 'es':
      return LocaleKey.es;
    case 'ko':
      return LocaleKey.ko;
    case 'de':
      return LocaleKey.de;
    case 'fr':
      return LocaleKey.fr;
    case 'pt':
      return LocaleKey.pt;
    case 'id':
      return LocaleKey.id;
    default:
      return LocaleKey.en;
  }
}


/// 国コードから、その言語での国名を返す。未知のコードは英語、それも無ければコードそのもの。
String localizedCountryName(String? raw, LocaleKey locale) {
  final code = normalizeCountryCode(raw);
  if (code == null) {
    final trimmed = raw?.trim();
    return (trimmed == null || trimmed.isEmpty) ? '' : trimmed;
  }
  switch (locale) {
    case LocaleKey.en:
      return _en[code] ?? code;
    case LocaleKey.ja:
      return _ja[code] ?? _en[code] ?? code;
    case LocaleKey.zh:
      return _zh[code] ?? _en[code] ?? code;
    case LocaleKey.zhTw:
      return _zhTw[code] ?? _en[code] ?? code;
    case LocaleKey.hi:
      return _hi[code] ?? _en[code] ?? code;
    case LocaleKey.es:
      return _es[code] ?? _en[code] ?? code;
    case LocaleKey.ko:
      return _ko[code] ?? _en[code] ?? code;
    case LocaleKey.de:
      return _de[code] ?? _en[code] ?? code;
    case LocaleKey.fr:
      return _fr[code] ?? _en[code] ?? code;
    case LocaleKey.pt:
      return _pt[code] ?? _en[code] ?? code;
    case LocaleKey.ptBr:
      return _ptBr[code] ?? _en[code] ?? code;
    case LocaleKey.id:
      return _id[code] ?? _en[code] ?? code;
  }
}

const _en = <String, String>{
  'AD': 'Andorra',
  'AE': 'United Arab Emirates',
  'AF': 'Afghanistan',
  'AG': 'Antigua and Barbuda',
  'AI': 'Anguilla',
  'AL': 'Albania',
  'AM': 'Armenia',
  'AO': 'Angola',
  'AR': 'Argentina',
  'AS': 'American Samoa',
  'AT': 'Austria',
  'AU': 'Australia',
  'AW': 'Aruba',
  'AX': 'Åland Islands',
  'AZ': 'Azerbaijan',
  'BA': 'Bosnia and Herzegovina',
  'BB': 'Barbados',
  'BD': 'Bangladesh',
  'BE': 'Belgium',
  'BF': 'Burkina Faso',
  'BG': 'Bulgaria',
  'BH': 'Bahrain',
  'BI': 'Burundi',
  'BJ': 'Benin',
  'BL': 'Saint Barthélemy',
  'BM': 'Bermuda',
  'BN': 'Brunei',
  'BO': 'Bolivia',
  'BQ': 'Caribbean Netherlands',
  'BR': 'Brazil',
  'BS': 'Bahamas',
  'BT': 'Bhutan',
  'BW': 'Botswana',
  'BY': 'Belarus',
  'BZ': 'Belize',
  'CA': 'Canada',
  'CC': 'Cocos (Keeling) Islands',
  'CD': 'Democratic Republic of the Congo',
  'CF': 'Central African Republic',
  'CG': 'Republic of the Congo',
  'CH': 'Switzerland',
  'CI': 'Côte d\'Ivoire',
  'CK': 'Cook Islands',
  'CL': 'Chile',
  'CM': 'Cameroon',
  'CN': 'China',
  'CO': 'Colombia',
  'CR': 'Costa Rica',
  'CU': 'Cuba',
  'CV': 'Cabo Verde',
  'CW': 'Curaçao',
  'CX': 'Christmas Island',
  'CY': 'Cyprus',
  'CZ': 'Czechia',
  'DE': 'Germany',
  'DJ': 'Djibouti',
  'DK': 'Denmark',
  'DM': 'Dominica',
  'DO': 'Dominican Republic',
  'DZ': 'Algeria',
  'EC': 'Ecuador',
  'EE': 'Estonia',
  'EG': 'Egypt',
  'ER': 'Eritrea',
  'ES': 'Spain',
  'ET': 'Ethiopia',
  'FI': 'Finland',
  'FJ': 'Fiji',
  'FK': 'Falkland Islands',
  'FM': 'Micronesia',
  'FO': 'Faroe Islands',
  'FR': 'France',
  'GA': 'Gabon',
  'GB': 'United Kingdom',
  'GD': 'Grenada',
  'GE': 'Georgia',
  'GF': 'French Guiana',
  'GG': 'Guernsey',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GL': 'Greenland',
  'GM': 'Gambia',
  'GN': 'Guinea',
  'GP': 'Guadeloupe',
  'GQ': 'Equatorial Guinea',
  'GR': 'Greece',
  'GT': 'Guatemala',
  'GU': 'Guam',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HK': 'Hong Kong',
  'HN': 'Honduras',
  'HR': 'Croatia',
  'HT': 'Haiti',
  'HU': 'Hungary',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IM': 'Isle of Man',
  'IN': 'India',
  'IQ': 'Iraq',
  'IR': 'Iran',
  'IS': 'Iceland',
  'IT': 'Italy',
  'JE': 'Jersey',
  'JM': 'Jamaica',
  'JO': 'Jordan',
  'JP': 'Japan',
  'KE': 'Kenya',
  'KG': 'Kyrgyzstan',
  'KH': 'Cambodia',
  'KI': 'Kiribati',
  'KM': 'Comoros',
  'KN': 'Saint Kitts and Nevis',
  'KP': 'North Korea',
  'KR': 'South Korea',
  'KW': 'Kuwait',
  'KY': 'Cayman Islands',
  'KZ': 'Kazakhstan',
  'LA': 'Laos',
  'LB': 'Lebanon',
  'LC': 'Saint Lucia',
  'LI': 'Liechtenstein',
  'LK': 'Sri Lanka',
  'LR': 'Liberia',
  'LS': 'Lesotho',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'LV': 'Latvia',
  'LY': 'Libya',
  'MA': 'Morocco',
  'MC': 'Monaco',
  'MD': 'Moldova',
  'ME': 'Montenegro',
  'MF': 'Saint Martin',
  'MG': 'Madagascar',
  'MH': 'Marshall Islands',
  'MK': 'North Macedonia',
  'ML': 'Mali',
  'MM': 'Myanmar',
  'MN': 'Mongolia',
  'MO': 'Macao',
  'MP': 'Northern Mariana Islands',
  'MQ': 'Martinique',
  'MR': 'Mauritania',
  'MS': 'Montserrat',
  'MT': 'Malta',
  'MU': 'Mauritius',
  'MV': 'Maldives',
  'MW': 'Malawi',
  'MX': 'Mexico',
  'MY': 'Malaysia',
  'MZ': 'Mozambique',
  'NA': 'Namibia',
  'NC': 'New Caledonia',
  'NE': 'Niger',
  'NF': 'Norfolk Island',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'NP': 'Nepal',
  'NR': 'Nauru',
  'NU': 'Niue',
  'NZ': 'New Zealand',
  'OM': 'Oman',
  'PA': 'Panama',
  'PE': 'Peru',
  'PF': 'French Polynesia',
  'PG': 'Papua New Guinea',
  'PH': 'Philippines',
  'PK': 'Pakistan',
  'PL': 'Poland',
  'PM': 'Saint Pierre and Miquelon',
  'PR': 'Puerto Rico',
  'PS': 'Palestine',
  'PT': 'Portugal',
  'PW': 'Palau',
  'PY': 'Paraguay',
  'QA': 'Qatar',
  'RE': 'Réunion',
  'RO': 'Romania',
  'RS': 'Serbia',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'SA': 'Saudi Arabia',
  'SB': 'Solomon Islands',
  'SC': 'Seychelles',
  'SD': 'Sudan',
  'SE': 'Sweden',
  'SG': 'Singapore',
  'SH': 'Saint Helena',
  'SI': 'Slovenia',
  'SK': 'Slovakia',
  'SL': 'Sierra Leone',
  'SM': 'San Marino',
  'SN': 'Senegal',
  'SO': 'Somalia',
  'SR': 'Suriname',
  'SS': 'South Sudan',
  'ST': 'São Tomé and Príncipe',
  'SV': 'El Salvador',
  'SX': 'Sint Maarten',
  'SZ': 'Eswatini',
  'TC': 'Turks and Caicos Islands',
  'TD': 'Chad',
  'TG': 'Togo',
  'TH': 'Thailand',
  'TJ': 'Tajikistan',
  'TL': 'Timor-Leste',
  'TM': 'Turkmenistan',
  'TN': 'Tunisia',
  'TO': 'Tonga',
  'TR': 'Türkiye',
  'TT': 'Trinidad and Tobago',
  'TV': 'Tuvalu',
  'TW': 'Taiwan',
  'TZ': 'Tanzania',
  'UA': 'Ukraine',
  'UG': 'Uganda',
  'US': 'United States',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VA': 'Vatican City',
  'VC': 'Saint Vincent and the Grenadines',
  'VE': 'Venezuela',
  'VG': 'British Virgin Islands',
  'VI': 'U.S. Virgin Islands',
  'VN': 'Vietnam',
  'VU': 'Vanuatu',
  'WF': 'Wallis and Futuna',
  'WS': 'Samoa',
  'XK': 'Kosovo',
  'YE': 'Yemen',
  'YT': 'Mayotte',
  'ZA': 'South Africa',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
};
const _ja = <String, String>{
  'AD': 'アンドラ',
  'AE': 'アラブ首長国連邦',
  'AF': 'アフガニスタン',
  'AG': 'アンティグア・バーブーダ',
  'AI': 'アンギラ',
  'AL': 'アルバニア',
  'AM': 'アルメニア',
  'AO': 'アンゴラ',
  'AR': 'アルゼンチン',
  'AS': '米領サモア',
  'AT': 'オーストリア',
  'AU': 'オーストラリア',
  'AW': 'アルバ',
  'AX': 'オーランド諸島',
  'AZ': 'アゼルバイジャン',
  'BA': 'ボスニア・ヘルツェゴビナ',
  'BB': 'バルバドス',
  'BD': 'バングラデシュ',
  'BE': 'ベルギー',
  'BF': 'ブルキナファソ',
  'BG': 'ブルガリア',
  'BH': 'バーレーン',
  'BI': 'ブルンジ',
  'BJ': 'ベナン',
  'BL': 'サン・バルテルミー',
  'BM': 'バミューダ',
  'BN': 'ブルネイ',
  'BO': 'ボリビア',
  'BQ': 'ボネール、シント・ユースタティウスおよびサバ',
  'BR': 'ブラジル',
  'BS': 'バハマ',
  'BT': 'ブータン',
  'BW': 'ボツワナ',
  'BY': 'ベラルーシ',
  'BZ': 'ベリーズ',
  'CA': 'カナダ',
  'CC': 'ココス（キーリング）諸島',
  'CD': 'コンゴ民主共和国',
  'CF': '中央アフリカ共和国',
  'CG': 'コンゴ共和国',
  'CH': 'スイス',
  'CI': 'コートジボワール',
  'CK': 'クック諸島',
  'CL': 'チリ',
  'CM': 'カメルーン',
  'CN': '中国',
  'CO': 'コロンビア',
  'CR': 'コスタリカ',
  'CU': 'キューバ',
  'CV': 'カーボベルデ',
  'CW': 'キュラソー',
  'CX': 'クリスマス島',
  'CY': 'キプロス',
  'CZ': 'チェコ',
  'DE': 'ドイツ',
  'DJ': 'ジブチ',
  'DK': 'デンマーク',
  'DM': 'ドミニカ国',
  'DO': 'ドミニカ共和国',
  'DZ': 'アルジェリア',
  'EC': 'エクアドル',
  'EE': 'エストニア',
  'EG': 'エジプト',
  'ER': 'エリトリア',
  'ES': 'スペイン',
  'ET': 'エチオピア',
  'FI': 'フィンランド',
  'FJ': 'フィジー',
  'FK': 'フォークランド諸島',
  'FM': 'ミクロネシア連邦',
  'FO': 'フェロー諸島',
  'FR': 'フランス',
  'GA': 'ガボン',
  'GB': 'イギリス',
  'GD': 'グレナダ',
  'GE': 'ジョージア',
  'GF': 'フランス領ギアナ',
  'GG': 'ガーンジー',
  'GH': 'ガーナ',
  'GI': 'ジブラルタル',
  'GL': 'グリーンランド',
  'GM': 'ガンビア',
  'GN': 'ギニア',
  'GP': 'グアドループ',
  'GQ': '赤道ギニア',
  'GR': 'ギリシャ',
  'GT': 'グアテマラ',
  'GU': 'グアム',
  'GW': 'ギニアビサウ',
  'GY': 'ガイアナ',
  'HK': '香港',
  'HN': 'ホンジュラス',
  'HR': 'クロアチア',
  'HT': 'ハイチ',
  'HU': 'ハンガリー',
  'ID': 'インドネシア',
  'IE': 'アイルランド',
  'IL': 'イスラエル',
  'IM': 'マン島',
  'IN': 'インド',
  'IQ': 'イラク',
  'IR': 'イラン',
  'IS': 'アイスランド',
  'IT': 'イタリア',
  'JE': 'ジャージー',
  'JM': 'ジャマイカ',
  'JO': 'ヨルダン',
  'JP': '日本',
  'KE': 'ケニア',
  'KG': 'キルギス',
  'KH': 'カンボジア',
  'KI': 'キリバス',
  'KM': 'コモロ',
  'KN': 'セントクリストファー・ネイビス',
  'KP': '北朝鮮',
  'KR': '韓国',
  'KW': 'クウェート',
  'KY': 'ケイマン諸島',
  'KZ': 'カザフスタン',
  'LA': 'ラオス',
  'LB': 'レバノン',
  'LC': 'セントルシア',
  'LI': 'リヒテンシュタイン',
  'LK': 'スリランカ',
  'LR': 'リベリア',
  'LS': 'レソト',
  'LT': 'リトアニア',
  'LU': 'ルクセンブルク',
  'LV': 'ラトビア',
  'LY': 'リビア',
  'MA': 'モロッコ',
  'MC': 'モナコ',
  'MD': 'モルドバ',
  'ME': 'モンテネグロ',
  'MF': 'サン・マルタン',
  'MG': 'マダガスカル',
  'MH': 'マーシャル諸島',
  'MK': '北マケドニア',
  'ML': 'マリ',
  'MM': 'ミャンマー',
  'MN': 'モンゴル',
  'MO': 'マカオ',
  'MP': '北マリアナ諸島',
  'MQ': 'マルティニーク',
  'MR': 'モーリタニア',
  'MS': 'モントセラト',
  'MT': 'マルタ',
  'MU': 'モーリシャス',
  'MV': 'モルディブ',
  'MW': 'マラウイ',
  'MX': 'メキシコ',
  'MY': 'マレーシア',
  'MZ': 'モザンビーク',
  'NA': 'ナミビア',
  'NC': 'ニューカレドニア',
  'NE': 'ニジェール',
  'NF': 'ノーフォーク島',
  'NG': 'ナイジェリア',
  'NI': 'ニカラグア',
  'NL': 'オランダ',
  'NO': 'ノルウェー',
  'NP': 'ネパール',
  'NR': 'ナウル',
  'NU': 'ニウエ',
  'NZ': 'ニュージーランド',
  'OM': 'オマーン',
  'PA': 'パナマ',
  'PE': 'ペルー',
  'PF': 'フランス領ポリネシア',
  'PG': 'パプアニューギニア',
  'PH': 'フィリピン',
  'PK': 'パキスタン',
  'PL': 'ポーランド',
  'PM': 'サンピエール島・ミクロン島',
  'PR': 'プエルトリコ',
  'PS': 'パレスチナ',
  'PT': 'ポルトガル',
  'PW': 'パラオ',
  'PY': 'パラグアイ',
  'QA': 'カタール',
  'RE': 'レユニオン',
  'RO': 'ルーマニア',
  'RS': 'セルビア',
  'RU': 'ロシア',
  'RW': 'ルワンダ',
  'SA': 'サウジアラビア',
  'SB': 'ソロモン諸島',
  'SC': 'セーシェル',
  'SD': 'スーダン',
  'SE': 'スウェーデン',
  'SG': 'シンガポール',
  'SH': 'セントヘレナ',
  'SI': 'スロベニア',
  'SK': 'スロバキア',
  'SL': 'シエラレオネ',
  'SM': 'サンマリノ',
  'SN': 'セネガル',
  'SO': 'ソマリア',
  'SR': 'スリナム',
  'SS': '南スーダン',
  'ST': 'サントメ・プリンシペ',
  'SV': 'エルサルバドル',
  'SX': 'シント・マールテン',
  'SZ': 'エスワティニ',
  'TC': 'タークス・カイコス諸島',
  'TD': 'チャド',
  'TG': 'トーゴ',
  'TH': 'タイ',
  'TJ': 'タジキスタン',
  'TL': '東ティモール',
  'TM': 'トルクメニスタン',
  'TN': 'チュニジア',
  'TO': 'トンガ',
  'TR': 'トルコ',
  'TT': 'トリニダード・トバゴ',
  'TV': 'ツバル',
  'TW': '台湾',
  'TZ': 'タンザニア',
  'UA': 'ウクライナ',
  'UG': 'ウガンダ',
  'US': 'アメリカ合衆国',
  'UY': 'ウルグアイ',
  'UZ': 'ウズベキスタン',
  'VA': 'バチカン市国',
  'VC': 'セントビンセント及びグレナディーン諸島',
  'VE': 'ベネズエラ',
  'VG': '英領ヴァージン諸島',
  'VI': '米領ヴァージン諸島',
  'VN': 'ベトナム',
  'VU': 'バヌアツ',
  'WF': 'ウォリス・フツナ',
  'WS': 'サモア',
  'XK': 'コソボ',
  'YE': 'イエメン',
  'YT': 'マヨット',
  'ZA': '南アフリカ',
  'ZM': 'ザンビア',
  'ZW': 'ジンバブエ',
};
const _zh = <String, String>{
  'AE': '阿联酋',
  'AR': '阿根廷',
  'AT': '奥地利',
  'AU': '澳大利亚',
  'BD': '孟加拉国',
  'BE': '比利时',
  'BR': '巴西',
  'BT': '不丹',
  'CA': '加拿大',
  'CH': '瑞士',
  'CL': '智利',
  'CN': '中国',
  'CO': '哥伦比亚',
  'DE': '德国',
  'DK': '丹麦',
  'EG': '埃及',
  'ES': '西班牙',
  'FI': '芬兰',
  'FR': '法国',
  'GB': '英国',
  'HK': '香港',
  'ID': '印度尼西亚',
  'IN': '印度',
  'IT': '意大利',
  'JP': '日本',
  'KR': '韩国',
  'MX': '墨西哥',
  'MY': '马来西亚',
  'NL': '荷兰',
  'NO': '挪威',
  'NP': '尼泊尔',
  'NZ': '新西兰',
  'PE': '秘鲁',
  'PH': '菲律宾',
  'PK': '巴基斯坦',
  'PL': '波兰',
  'PT': '葡萄牙',
  'RU': '俄罗斯',
  'SA': '沙特阿拉伯',
  'SE': '瑞典',
  'SG': '新加坡',
  'TH': '泰国',
  'TR': '土耳其',
  'TW': '台湾',
  'UA': '乌克兰',
  'US': '美国',
  'VN': '越南',
  'ZA': '南非',
};
const _zhTw = <String, String>{
  'AE': '阿聯',
  'AR': '阿根廷',
  'AT': '奧地利',
  'AU': '澳洲',
  'BD': '孟加拉',
  'BE': '比利時',
  'BR': '巴西',
  'BT': '不丹',
  'CA': '加拿大',
  'CH': '瑞士',
  'CL': '智利',
  'CN': '中國',
  'CO': '哥倫比亞',
  'DE': '德國',
  'DK': '丹麥',
  'EG': '埃及',
  'ES': '西班牙',
  'FI': '芬蘭',
  'FR': '法國',
  'GB': '英國',
  'HK': '香港',
  'ID': '印尼',
  'IN': '印度',
  'IT': '義大利',
  'JP': '日本',
  'KR': '韓國',
  'MX': '墨西哥',
  'MY': '馬來西亞',
  'NL': '荷蘭',
  'NO': '挪威',
  'NP': '尼泊爾',
  'NZ': '紐西蘭',
  'PE': '秘魯',
  'PH': '菲律賓',
  'PK': '巴基斯坦',
  'PL': '波蘭',
  'PT': '葡萄牙',
  'RU': '俄羅斯',
  'SA': '沙烏地阿拉伯',
  'SE': '瑞典',
  'SG': '新加坡',
  'TH': '泰國',
  'TR': '土耳其',
  'TW': '臺灣',
  'UA': '烏克蘭',
  'US': '美國',
  'VN': '越南',
  'ZA': '南非',
};
const _hi = <String, String>{
  'AE': 'संयुक्त अरब अमीरात',
  'AR': 'अर्जेंटीना',
  'AT': 'ऑस्ट्रिया',
  'AU': 'ऑस्ट्रेलिया',
  'BD': 'बांग्लादेश',
  'BE': 'बेल्जियम',
  'BR': 'ब्राज़ील',
  'BT': 'भूटान',
  'CA': 'कनाडा',
  'CH': 'स्विट्ज़रलैंड',
  'CL': 'चिली',
  'CN': 'चीन',
  'CO': 'कोलंबिया',
  'DE': 'जर्मनी',
  'DK': 'डेनमार्क',
  'EG': 'मिस्र',
  'ES': 'स्पेन',
  'FI': 'फिनलैंड',
  'FR': 'फ्रांस',
  'GB': 'यूनाइटेड किंगडम',
  'HK': 'हांग कांग',
  'ID': 'इंडोनेशिया',
  'IN': 'भारत',
  'IT': 'इटली',
  'JP': 'जापान',
  'KR': 'दक्षिण कोरिया',
  'MX': 'मेक्सिको',
  'MY': 'मलेशिया',
  'NL': 'नीदरलैंड',
  'NO': 'नॉर्वे',
  'NP': 'नेपाल',
  'NZ': 'न्यूज़ीलैंड',
  'PE': 'पेरू',
  'PH': 'फिलीपींस',
  'PK': 'पाकिस्तान',
  'PL': 'पोलैंड',
  'PT': 'पुर्तगाल',
  'RU': 'रूस',
  'SA': 'सऊदी अरब',
  'SE': 'स्वीडन',
  'SG': 'सिंगापुर',
  'TH': 'थाईलैंड',
  'TR': 'तुर्की',
  'TW': 'ताइवान',
  'UA': 'यूक्रेन',
  'US': 'संयुक्त राज्य अमेरिका',
  'VN': 'वियतनाम',
  'ZA': 'दक्षिण अफ्रीका',
};
const _es = <String, String>{
  'AE': 'Emiratos Árabes Unidos',
  'AR': 'Argentina',
  'AT': 'Austria',
  'AU': 'Australia',
  'BD': 'Bangladés',
  'BE': 'Bélgica',
  'BR': 'Brasil',
  'BT': 'Bután',
  'CA': 'Canadá',
  'CH': 'Suiza',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Colombia',
  'DE': 'Alemania',
  'DK': 'Dinamarca',
  'EG': 'Egipto',
  'ES': 'España',
  'FI': 'Finlandia',
  'FR': 'Francia',
  'GB': 'Reino Unido',
  'HK': 'Hong Kong',
  'ID': 'Indonesia',
  'IN': 'India',
  'IT': 'Italia',
  'JP': 'Japón',
  'KR': 'Corea del Sur',
  'MX': 'México',
  'MY': 'Malasia',
  'NL': 'Países Bajos',
  'NO': 'Noruega',
  'NP': 'Nepal',
  'NZ': 'Nueva Zelanda',
  'PE': 'Perú',
  'PH': 'Filipinas',
  'PK': 'Pakistán',
  'PL': 'Polonia',
  'PT': 'Portugal',
  'RU': 'Rusia',
  'SA': 'Arabia Saudita',
  'SE': 'Suecia',
  'SG': 'Singapur',
  'TH': 'Tailandia',
  'TR': 'Turquía',
  'TW': 'Taiwán',
  'UA': 'Ucrania',
  'US': 'Estados Unidos',
  'VN': 'Vietnam',
  'ZA': 'Sudáfrica',
};
const _ko = <String, String>{
  'AE': '아랍에미리트',
  'AR': '아르헨티나',
  'AT': '오스트리아',
  'AU': '호주',
  'BD': '방글라데시',
  'BE': '벨기에',
  'BR': '브라질',
  'BT': '부탄',
  'CA': '캐나다',
  'CH': '스위스',
  'CL': '칠레',
  'CN': '중국',
  'CO': '콜롬비아',
  'DE': '독일',
  'DK': '덴마크',
  'EG': '이집트',
  'ES': '스페인',
  'FI': '핀란드',
  'FR': '프랑스',
  'GB': '영국',
  'HK': '홍콩',
  'ID': '인도네시아',
  'IN': '인도',
  'IT': '이탈리아',
  'JP': '일본',
  'KR': '대한민국',
  'MX': '멕시코',
  'MY': '말레이시아',
  'NL': '네덜란드',
  'NO': '노르웨이',
  'NP': '네팔',
  'NZ': '뉴질랜드',
  'PE': '페루',
  'PH': '필리핀',
  'PK': '파키스탄',
  'PL': '폴란드',
  'PT': '포르투갈',
  'RU': '러시아',
  'SA': '사우디아라비아',
  'SE': '스웨덴',
  'SG': '싱가포르',
  'TH': '태국',
  'TR': '튀르키예',
  'TW': '대만',
  'UA': '우크라이나',
  'US': '미국',
  'VN': '베트남',
  'ZA': '남아프리카',
};
const _de = <String, String>{
  'AE': 'Vereinigte Arabische Emirate',
  'AR': 'Argentinien',
  'AT': 'Österreich',
  'AU': 'Australien',
  'BD': 'Bangladesch',
  'BE': 'Belgien',
  'BR': 'Brasilien',
  'BT': 'Bhutan',
  'CA': 'Kanada',
  'CH': 'Schweiz',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Kolumbien',
  'DE': 'Deutschland',
  'DK': 'Dänemark',
  'EG': 'Ägypten',
  'ES': 'Spanien',
  'FI': 'Finnland',
  'FR': 'Frankreich',
  'GB': 'Vereinigtes Königreich',
  'HK': 'Hongkong',
  'ID': 'Indonesien',
  'IN': 'Indien',
  'IT': 'Italien',
  'JP': 'Japan',
  'KR': 'Südkorea',
  'MX': 'Mexiko',
  'MY': 'Malaysia',
  'NL': 'Niederlande',
  'NO': 'Norwegen',
  'NP': 'Nepal',
  'NZ': 'Neuseeland',
  'PE': 'Peru',
  'PH': 'Philippinen',
  'PK': 'Pakistan',
  'PL': 'Polen',
  'PT': 'Portugal',
  'RU': 'Russland',
  'SA': 'Saudi-Arabien',
  'SE': 'Schweden',
  'SG': 'Singapur',
  'TH': 'Thailand',
  'TR': 'Türkei',
  'TW': 'Taiwan',
  'UA': 'Ukraine',
  'US': 'Vereinigte Staaten',
  'VN': 'Vietnam',
  'ZA': 'Südafrika',
};
const _fr = <String, String>{
  'AE': 'Émirats arabes unis',
  'AR': 'Argentine',
  'AT': 'Autriche',
  'AU': 'Australie',
  'BD': 'Bangladesh',
  'BE': 'Belgique',
  'BR': 'Brésil',
  'BT': 'Bhoutan',
  'CA': 'Canada',
  'CH': 'Suisse',
  'CL': 'Chili',
  'CN': 'Chine',
  'CO': 'Colombie',
  'DE': 'Allemagne',
  'DK': 'Danemark',
  'EG': 'Égypte',
  'ES': 'Espagne',
  'FI': 'Finlande',
  'FR': 'France',
  'GB': 'Royaume-Uni',
  'HK': 'Hong Kong',
  'ID': 'Indonésie',
  'IN': 'Inde',
  'IT': 'Italie',
  'JP': 'Japon',
  'KR': 'Corée du Sud',
  'MX': 'Mexique',
  'MY': 'Malaisie',
  'NL': 'Pays-Bas',
  'NO': 'Norvège',
  'NP': 'Népal',
  'NZ': 'Nouvelle-Zélande',
  'PE': 'Pérou',
  'PH': 'Philippines',
  'PK': 'Pakistan',
  'PL': 'Pologne',
  'PT': 'Portugal',
  'RU': 'Russie',
  'SA': 'Arabie saoudite',
  'SE': 'Suède',
  'SG': 'Singapour',
  'TH': 'Thaïlande',
  'TR': 'Turquie',
  'TW': 'Taïwan',
  'UA': 'Ukraine',
  'US': 'États-Unis',
  'VN': 'Viêt Nam',
  'ZA': 'Afrique du Sud',
};
const _pt = <String, String>{
  'AE': 'Emirados Árabes Unidos',
  'AR': 'Argentina',
  'AT': 'Áustria',
  'AU': 'Austrália',
  'BD': 'Bangladesh',
  'BE': 'Bélgica',
  'BR': 'Brasil',
  'BT': 'Butão',
  'CA': 'Canadá',
  'CH': 'Suíça',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Colômbia',
  'DE': 'Alemanha',
  'DK': 'Dinamarca',
  'EG': 'Egito',
  'ES': 'Espanha',
  'FI': 'Finlândia',
  'FR': 'França',
  'GB': 'Reino Unido',
  'HK': 'Hong Kong',
  'ID': 'Indonésia',
  'IN': 'Índia',
  'IT': 'Itália',
  'JP': 'Japão',
  'KR': 'Coreia do Sul',
  'MX': 'México',
  'MY': 'Malásia',
  'NL': 'Países Baixos',
  'NO': 'Noruega',
  'NP': 'Nepal',
  'NZ': 'Nova Zelândia',
  'PE': 'Peru',
  'PH': 'Filipinas',
  'PK': 'Paquistão',
  'PL': 'Polónia',
  'PT': 'Portugal',
  'RU': 'Rússia',
  'SA': 'Arábia Saudita',
  'SE': 'Suécia',
  'SG': 'Singapura',
  'TH': 'Tailândia',
  'TR': 'Turquia',
  'TW': 'Taiwan',
  'UA': 'Ucrânia',
  'US': 'Estados Unidos',
  'VN': 'Vietname',
  'ZA': 'África do Sul',
};
const _ptBr = <String, String>{
  'AE': 'Emirados Árabes Unidos',
  'AR': 'Argentina',
  'AT': 'Áustria',
  'AU': 'Austrália',
  'BD': 'Bangladesh',
  'BE': 'Bélgica',
  'BR': 'Brasil',
  'BT': 'Butão',
  'CA': 'Canadá',
  'CH': 'Suíça',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Colômbia',
  'DE': 'Alemanha',
  'DK': 'Dinamarca',
  'EG': 'Egito',
  'ES': 'Espanha',
  'FI': 'Finlândia',
  'FR': 'França',
  'GB': 'Reino Unido',
  'HK': 'Hong Kong',
  'ID': 'Indonésia',
  'IN': 'Índia',
  'IT': 'Itália',
  'JP': 'Japão',
  'KR': 'Coreia do Sul',
  'MX': 'México',
  'MY': 'Malásia',
  'NL': 'Países Baixos',
  'NO': 'Noruega',
  'NP': 'Nepal',
  'NZ': 'Nova Zelândia',
  'PE': 'Peru',
  'PH': 'Filipinas',
  'PK': 'Paquistão',
  'PL': 'Polônia',
  'PT': 'Portugal',
  'RU': 'Rússia',
  'SA': 'Arábia Saudita',
  'SE': 'Suécia',
  'SG': 'Singapura',
  'TH': 'Tailândia',
  'TR': 'Turquia',
  'TW': 'Taiwan',
  'UA': 'Ucrânia',
  'US': 'Estados Unidos',
  'VN': 'Vietnã',
  'ZA': 'África do Sul',
};
const _id = <String, String>{
  'AE': 'Uni Emirat Arab',
  'AR': 'Argentina',
  'AT': 'Austria',
  'AU': 'Australia',
  'BD': 'Bangladesh',
  'BE': 'Belgia',
  'BR': 'Brasil',
  'BT': 'Bhutan',
  'CA': 'Kanada',
  'CH': 'Swiss',
  'CL': 'Chile',
  'CN': 'Tiongkok',
  'CO': 'Kolombia',
  'DE': 'Jerman',
  'DK': 'Denmark',
  'EG': 'Mesir',
  'ES': 'Spanyol',
  'FI': 'Finlandia',
  'FR': 'Prancis',
  'GB': 'Britania Raya',
  'HK': 'Hong Kong',
  'ID': 'Indonesia',
  'IN': 'India',
  'IT': 'Italia',
  'JP': 'Jepang',
  'KR': 'Korea Selatan',
  'MX': 'Meksiko',
  'MY': 'Malaysia',
  'NL': 'Belanda',
  'NO': 'Norwegia',
  'NP': 'Nepal',
  'NZ': 'Selandia Baru',
  'PE': 'Peru',
  'PH': 'Filipina',
  'PK': 'Pakistan',
  'PL': 'Polandia',
  'PT': 'Portugal',
  'RU': 'Rusia',
  'SA': 'Arab Saudi',
  'SE': 'Swedia',
  'SG': 'Singapura',
  'TH': 'Thailand',
  'TR': 'Turki',
  'TW': 'Taiwan',
  'UA': 'Ukraina',
  'US': 'Amerika Serikat',
  'VN': 'Vietnam',
  'ZA': 'Afrika Selatan',
};
